# Author: Xiaoyang Wu (xiaoyang.wu@smartmore.com)
# Basic
NAME: "JHT"
SOURCE_DIR: "//192.168.10.100/Gofinge/Documents/Data/barcode_2d"
DATASET: {"JHT": "JHT", "halcon": "'halcon/ecc200", "dot_DM": "dot_datamatrix"}
TARGET: "JHT"
OUTPUT_DIR: "results"
USE_BAR: True

# Detector
DETECTOR:
  ENABLE: True
  # support method: "general", "gradient-edg", "max-min"
  METHOD: "gradient-edge"
  ARG: {}

# Decoder
DECODER:
  ENABLE: True
  METHOD: "line-cycle-zxing"
  ARG:
    zxing_enable: False

# Image
IMAGE:
  MAX_SIZE: 512
  MIN_SIZE: 256
  BINARIZER:
    METHOD: "general"
    LOCAL_WINDOWS_SIZE: 20
  GRAYSCALE:
    METHOD: "general"
  PYRAMID:
    FACTOR_LIST: [1, 2, 4]

