# Author: Xiaoyang Wu (xiaoyang.wu@smartmore.com)
# Basic
NAME: "halcon-detect"
SOURCE_DIR: "//192.168.6.186/SMore-X/bench_mark/twod/datamatrix"
DATASET: {"JHT": "JHT/data", "halcon": "halcon/ecc200", "dot_DM": "dot_datamatrix"}
TARGET: "JHT"
OUTPUT_DIR: "results"
USE_BAR: True

# Detector
DETECTOR:
  ENABLE: True
  # support method: "general", "gradient-edge", "max-min"
  METHOD: "dev"
  ARG: {}

# Decoder
DECODER:
  ENABLE: False
  METHOD: "line-cycle-zxing"
  ARG:
    zxing_enable: True

# Image
IMAGE:
  MAX_SIZE: 400
  MIN_SIZE: 256
  BINARIZER:
    METHOD: "general"
    LOCAL_WINDOWS_SIZE: 20
  GRAYSCALE:
    METHOD: "general"
  PYRAMID:
    FACTOR_LIST: [1, 2, 4]

