# Author: Xiaoyang Wu (xiaoyang.wu@smartmore.com)
# Basic
NAME: "JHT"
SOURCE_DIR: "//192.168.6.186/SMore-X/bench_mark/twod/datamatrix"
DATASET: {"JHT": "JHT/data", "halcon": "ecc200", "dot_DM": "dot_datamatrix"}
TARGET: "JHT"
OUTPUT_DIR: "results"
USE_BAR: True

# Detector
DETECTOR:
  ENABLE: True
  # support method: "general", "gradient-edge", "max-min"
  METHOD: "gradient-edge"
  ARG:
    num_pyramid_level: 4
    block_size: 150
    thread_offset: 30
    nms_iou_threshold: 0.95
    vis: False

# Decoder
DECODER:
  ENABLE: True
  METHOD: "line-cycle-zxing"
  ARG:
    zxing_enable: True

